
model:
  phrase_refinement_model:
    encoder_max_sequence_length: 1024
    decoder_max_sequence_length: 512
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
  phrase_generation_model:
    encoder_max_sequence_length: 2048
    decoder_max_sequence_length: 512
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
  phrase_selection_model:
    max_sequence_length: 512
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
    projection_size: 128
  structure_derivation_model:
    max_sequence_length: 1024
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
    projection_size: 128
  fusion_model:
    encoder_max_sequence_length: 1024
    decoder_max_sequence_length: 512
    num_layers: 12
    num_heads: 8
    hidden_size: 512
    intermediate_size: 2048

training:
  phrase_refinement:
    epochs: 30
    batch_size: 128
    learning_rate: 0.0001
    validation_split: 0.1
    test_split: 100
    weight_decay: 0.01
    max_grad_norm: 3.0
    gradient_accumulation_steps: 1
  phrase_generation:
    epochs: 30
    batch_size: 56
    learning_rate: 0.0001
    weight_decay: 0.01
    max_grad_norm: 3.0
    gradient_accumulation_steps: 1
  phrase_selection:
    epochs: 30
    batch_size: 256
    learning_rate: 0.0001
    weight_decay: 0.01
    gradient_accumulation_steps: 1
  structure_derivation:
    epochs: 30
    batch_size: 128
    learning_rate: 0.0001
    weight_decay: 0.01
    gradient_accumulation_steps: 1
  fusion:
    epochs: 700
    batch_size: 80
    learning_rate: 0.0001
    weight_decay: 0.01
    gradient_accumulation_steps: 1

raw_data:
  raw_data_folders: 
    dataset_1: 
      folder_path: C:/Users/Keshav/Desktop/QMUL/Research/Datasets/MTC/essen
      file_extension: krn
      annotation_filepath: data/annotations/essen_sequences-1.1.jsonl/essen_sequences.jsonl
    dataset_2: 
      folder_path: C:/Users/Keshav/Desktop/QMUL/Research/Datasets/MTC/mtc-ann-2.0.1/MTC-ANN-2.0.1/krn
      file_extension: krn
      annotation_filepath: data/annotations/MTC-ANN-2.0.1_sequences-1.1.jsonl/mtcann_sequences.jsonl
    dataset_3: 
      folder_path: C:/Users/Keshav/Desktop/QMUL/Research/Datasets/MTC/MTC-FS-INST-2.0/MTC-FS-INST-2.0/krn
      file_extension: krn
      annotation_filepath: data/annotations/MTC-FS-INST-2.0_sequences-1.1.jsonl/mtcfsinst_sequences.jsonl
  mono_folder: data/Mono_Midi_Files
  json_folder: data/extracted_phrases
  artifact_folder: artifacts

generation:
  metadata:
    key_signature: "C"
    major_or_minor: "major"
    time_signature: "4/4" # "4/4", "3/4", "2/4", "6/8"
    tempo: 120
  prompt:
  # The prompt is a list of lists, where each inner list represents a note.
  # Each note is represented by a list of six values: [Bar number, onset, instrument, pitch, duration, velocity]
  # Duration value of 1 means a quarter note, 0.5 means an eighth note, etc.
  # The values are as follows following the example of Twinkle Twinkle:
    phrase_1: [[0,0,0,60,0.5,91], [0,0.5,0,60,0.5,91], [0,1,0,67,0.5,91], [0,1.5,0,67,0.5,91], [0,2,0,69,0.5,91], [0,2.5,0,69,0.5,91], [0,3,0,67,1,91], [1,0,0,65,0.5,91], [1,0.5,0,65,0.5,91], [1,1,0,64,0.5,91], [1,1.5,0,64,0.5,91], [1,2,0,62,0.5,91], [1,2.5,0,62,0.5,91], [1,3,0,60,1,91]]
    # phrase_1: [[0,0,0,62,0.25,91],[0,0.25,0,62,0.25,91],[0,0.5,0,67,0.5,91],[0,1,0,67,0.5,91],[0,1.5,0,71,0.5,91],[1,0,0,71,0.25,91],[1,0.25,0,71,0.25,91],[1,0.5,0,74,0.5,91],[1,1,0,76,0.25,91],[1,1.25,0,74,0.25,91],[1,1.5,0,71,0.5,91],[2,0,0,71,0.25,91],[2,0.25,0,71,0.25,91],[2,0.5,0,74,0.5,91],[2,1,0,72,0.5,91],[2,1.5,0,69,0.5,91],[3,0,0,69,0.25,91],[3,0.25,0,69,0.25,91],[3,0.5,0,71,0.5,91],[3,1,0,79,0.5,91],[3,1.5,0,83,0.5,91]]
  use_velocity: false
  use_phrase_selection: false
  structure: ABBBAA
  phrases_per_section: [5, 1, 1, 5, 5, 3]
  transformations: [] # "contract_melody", "retrograde_melody_pitch_rhythm", "reduce_melody", "invert_melody_tonal", "expand_melody"
  allow_modulation: false
  ratio:
    phrase_generation_frequency: 2
    phrase_refinement_frequency: 1
    motif_repetition_frequency: 50
  write_midi: false # Change to false to write to mxl