
model:
  phrase_refinement_model:
    encoder_max_sequence_length: 1024
    decoder_max_sequence_length: 512
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
  phrase_generation_model:
    encoder_max_sequence_length: 2048
    decoder_max_sequence_length: 512
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
  phrase_chooser_model:
    max_sequence_length: 1024
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
    projection_size: 128
  phrase_selection_model:
    max_sequence_length: 1024
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048
    projection_size: 128
  motif_refinement_model:
    encoder_max_sequence_length: 512
    decoder_max_sequence_length: 512
    num_layers: 4
    num_heads: 4
    hidden_size: 512
    intermediate_size: 2048

training:
  phrase_refinement:
    epochs: 30
    batch_size: 64
    learning_rate: 0.0001
    validation_split: 0.1
    test_split: 100
    weight_decay: 0.01
    gradient_accumulation_steps: 1
  phrase_generation:
    epochs: 30
    batch_size: 48
    learning_rate: 0.0001
    weight_decay: 0.01
    gradient_accumulation_steps: 1
  phrase_chooser:
    epochs: 30
    batch_size: 64
    learning_rate: 0.0003
    # weight_decay: 0.000001
    temperature: 0.5
    gradient_accumulation_steps: 1
  phrase_selection:
    epochs: 30
    batch_size: 64
    learning_rate: 0.0001
    weight_decay: 0.000001
    gradient_accumulation_steps: 1
  motif_refinement:
    epochs: 30
    batch_size: 64
    learning_rate: 0.0001
    weight_decay: 0.01
    gradient_accumulation_steps: 1

raw_data:
  raw_data_folders: 
    dataset_1: 
      folder_path: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\MTC\essen
      file_extension: krn
      annotation_filepath: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\MTC\3551003\essen_sequences-1.1.jsonl\essen_sequences.jsonl
    dataset_2: 
      folder_path: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\MTC\mtc-ann-2.0.1\MTC-ANN-2.0.1\krn
      file_extension: krn
      annotation_filepath: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\MTC\3551003\MTC-ANN-2.0.1_sequences-1.1.jsonl\mtcann_sequences.jsonl
    dataset_3: 
      folder_path: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\MTC\MTC-FS-INST-2.0\MTC-FS-INST-2.0\krn
      file_extension: krn
      annotation_filepath: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\MTC\3551003\MTC-FS-INST-2.0_sequences-1.1.jsonl\mtcfsinst_sequences.jsonl
  mono_folder: data\Mono_Midi_Files
  json_folder: data\extracted_phrases
  artifact_folder: artifacts
  
  # # midi_folder: C:\Users\Keshav\Desktop\QMUL\Research\Datasets\Mono_Midi_Files #\Essen_mono #C:\Users\Keshav\Desktop\QMUL\Research\Datasets\Mono_Midi_Files\Wikifonia_mono
  # json_folder: C:\Users\Keshav\Desktop\QMUL\Research\melodic-development\phrase_refinement\extracted_phrases\extracted_phrases_all #phrase_refinement/extracted_phrases/extracted_phrases_wikifonia
  # artifact_folder: C:\Users\Keshav\Desktop\QMUL\Research\melodic-development\phrase_refinement\artifacts #/homes/kb658/melodic-development/phrase_refinement/artifacts
  # tokenizer_filename: tokenizer.json
  # remi_tokenizer_filename: remi_tokenizer.pickle

generation:
  test_filepath: null
  structure: ABA
  phrases_per_section: [4, 4, 4]
  ratio:
    phrase_generation_frequency: 1
    phrase_refinement_frequency: 1
    motif_repetition_frequency: 4
